# Imported Libraries

In [2]:
import numpy as np
import pandas as pd

# reading chatbot.txt and converting into df_chatbot_text dataframe

In [29]:
fo=open("chatbot.txt","r")
chatbot_data=fo.read()
fo.close()

In [30]:
list_of_sentences=chatbot_data.replace("\t"," ").split("\n")
list_of_sentences.pop(-1),"this is an empty string so it is being deleted from the list"

('', 'this is an empty string so it is being deleted from the list')

In [31]:
len(list_of_sentences)

566

In [36]:
chatbot_text_dictionary={}
chatbot_text_dictionary["Response"]=list_of_sentences
chatbot_text_dictionary["Label"]=[0 for i in range(len(list_of_sentences))]
df_chatbot_text=pd.DataFrame(chatbot_text_dictionary)
print(df_chatbot_text.shape)
df_chatbot_text.head(3)

(566, 2)

                                            Response  Label
0  What are your interests I am interested in all...      0
1  What are your favorite subjects My favorite su...      0
2  What are your interests I am interested in a w...      0

# reading sheet_1.csv and converting into df_sheet1 dataframe

In [74]:
df_sheet1=pd.read_csv("sheet_1.csv")

In [75]:
df_sheet1.head()

,response_id,class,response_text,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,response_1,not_flagged,I try and avoid this sort of conflict,NaN,NaN,NaN,NaN,NaN
1,response_2,flagged,Had a friend open up to me about his mental ad...,NaN,NaN,NaN,NaN,NaN
2,response_3,flagged,I saved a girl from suicide once. She was goin...,NaN,NaN,NaN,NaN,NaN
3,response_4,not_flagged,i cant think of one really...i think i may hav...,NaN,NaN,NaN,NaN,NaN
4,response_5,not_flagged,Only really one friend who doesn't fit into th...,,NaN,NaN,NaN,NaN

In [81]:
df_sheet1["Response"]=df_sheet1["response_text"]
df_sheet1["Label"]=[0 for i in range(len(df_sheet1["Response"]))]
df_sheet1.drop(labels=["response_id","class","response_text","Unnamed: 3","Unnamed: 4","Unnamed: 5","Unnamed: 6","Unnamed: 7"],axis=1,inplace=True)

In [82]:
df_sheet1

                                             Response  Label
0               I try and avoid this sort of conflict      0
1   Had a friend open up to me about his mental ad...      0
2   I saved a girl from suicide once. She was goin...      0
3   i cant think of one really...i think i may hav...      0
4   Only really one friend who doesn't fit into th...      0
..                                                ...    ...
75  Now that I've been through it, although i'm no...      0
76  when my best friends mom past away from od'ing...      0
77  As a camp counselor I provide stability in kid...      0
78  My now girlfriend used to have serious addicti...      0
79  The one person I ever talked to it was because...      0

[80 rows x 2 columns]

# reading sheet_2.csv and converting into df_sheet2 dataframe

In [45]:
df_sheet2=pd.read_csv("sheet_2.csv")

In [46]:
df_sheet2.head()

  resume_id        class                                        resume_text
0  resume_1  not_flagged  \rCustomer Service Supervisor/Tier - Isabella ...
1  resume_2  not_flagged  \rEngineer / Scientist - IBM Microelectronics ...
2  resume_3  not_flagged  \rLTS Software Engineer Computational Lithogra...
3  resume_4  not_flagged   TUTOR\rWilliston VT - Email me on Indeed: ind...
4  resume_5      flagged  \rIndependent Consultant - Self-employed\rBurl...

In [51]:
df_sheet2["resume_text"]=[i.replace("\r","").split("-")[0] for i in df_sheet2["resume_text"]]

In [52]:
df_sheet2.head()

  resume_id        class                                       resume_text
0  resume_1  not_flagged                 Customer Service Supervisor/Tier
1  resume_2  not_flagged                             Engineer / Scientist
2  resume_3  not_flagged  LTS Software Engineer Computational Lithography
3  resume_4  not_flagged                                TUTORWilliston VT
4  resume_5      flagged                           Independent Consultant

In [61]:
df_sheet2["Response"]=df_sheet2["resume_text"]
df_sheet2["Label"]=[0 for i in range(len(df_sheet2["Response"]))]
df_sheet2.drop(labels=["resume_id","class","resume_text"],axis=1,inplace=True)

In [63]:
print(df_sheet2.shape)
df_sheet2.head()

(125, 2)

                                           Response  Label
0                 Customer Service Supervisor/Tier       0
1                             Engineer / Scientist       0
2  LTS Software Engineer Computational Lithography       0
3                                TUTORWilliston VT       0
4                           Independent Consultant       0

# reading sheet_3.csv and converting into df_sheet3 dataframe

In [114]:
df_sheet3=pd.read_csv("sheet3.csv")

In [115]:
df_sheet3.shape

(21534, 4)

In [116]:
df_sheet3.head()

,flags,utterance,category,intent
0,BILC,"I don't have an online account, what do I have...",ACCOUNT,create_account
1,BILQZ,can you tell me if i can regisger two accounts...,ACCOUNT,create_account
2,BPLC,"I have no online account, open one, please",ACCOUNT,create_account
3,BIPLD,"could you ask an agent how to open an account,...",ACCOUNT,create_account
4,BLQC,"i want an online account, create one",ACCOUNT,create_account

In [117]:
df_sheet3["Response"]=df_sheet3["utterance"]
df_sheet3["Label"]=[0 for i in range(len(df_sheet3["Response"]))]
df_sheet3.drop(labels=["flags","utterance","category","intent"],axis=1,inplace=True)

In [122]:
print("before :",df_sheet3.shape)
df_sheet3=df_sheet3.iloc[:3767,:]
print("after :",df_sheet3.shape)
print("number of label values are")
print(df_sheet3["Label"].value_counts())
df_sheet3.head()

before : (3767, 2)
after : (3767, 2)
number of label values are
0    3767
Name: Label, dtype: int64

                                            Response  Label
0  I don't have an online account, what do I have...      0
1  can you tell me if i can regisger two accounts...      0
2         I have no online account, open one, please      0
3  could you ask an agent how to open an account,...      0
4               i want an online account, create one      0

# reading gibberish.csv and converting into df_gibberish dataframe

In [101]:
df_gibberish=pd.read_csv("Gibberish.csv")

In [113]:
print("number of label values",df_gibberish["Label"].value_counts())
df_gibberish.head()

number of label values 1    3767
Name: Label, dtype: int64

                      Response  Label
0                          ggg      1
1             hgghghghghghghhg      1
2  ufdhgjndfnvbhfdjvnjkmfgbdfg      1
3                      dbdbdbd      1
4                      dfgdfgd      1

# Combining df_sheet3 and df_gibberish to df_main

In [125]:
df_main=pd.concat([df_gibberish,df_sheet3],ignore_index=True)
print(df_main.shape)
print("number of label values are")
print(df_main["Label"].value_counts())
df_main.head()

(7534, 2)
number of label values are
1    3767
0    3767
Name: Label, dtype: int64

                      Response  Label
0                          ggg      1
1             hgghghghghghghhg      1
2  ufdhgjndfnvbhfdjvnjkmfgbdfg      1
3                      dbdbdbd      1
4                      dfgdfgd      1

In [128]:
import tensorflow 
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [130]:
vocab=20000
tokenizer = Tokenizer(num_words=vocab)
tokenizer.fit_on_texts(df_main["Response"])

In [135]:
print("the length of vocabulary size is :",len(tokenizer.word_index))
tokenizer.word_index

the length of vocabulary size is : 6609

{'i': 1,
 'account': 2,
 'can': 3,
 'my': 4,
 'to': 5,
 'do': 6,
 'one': 7,
 'want': 8,
 'user': 9,
 'online': 10,
 'create': 11,
 'a': 12,
 'an': 13,
 'it': 14,
 'if': 15,
 'with': 16,
 'email': 17,
 'what': 18,
 'have': 19,
 'me': 20,
 'how': 21,
 'profile': 22,
 'register': 23,
 'help': 24,
 'you': 25,
 'the': 26,
 'accounts': 27,
 'no': 28,
 'got': 29,
 'password': 30,
 'tell': 31,
 'open': 32,
 'need': 33,
 'address': 34,
 'single': 35,
 'could': 36,
 'same': 37,
 'please': 38,
 "don't": 39,
 'several': 40,
 'ask': 41,
 'agent': 42,
 'than': 43,
 'more': 44,
 'mind': 45,
 'and': 46,
 'know': 47,
 'changed': 48,
 'two': 49,
 'u': 50,
 'remove': 51,
 'should': 52,
 'close': 53,
 'hacked': 54,
 'cancel': 55,
 'delete': 56,
 'recover': 57,
 'fucking': 58,
 'where': 59,
 'wanna': 60,
 "i've": 61,
 "haven't": 62,
 'profiles': 63,
 'retrieve': 64,
 'been': 65,
 'reset': 66,
 'dont': 67,
 'was': 68,
 'back': 69,
 'remember': 70,
 'like': 71,
 'lost': 72,
 'get': 73,
 'information': 74,
 'on': 75,
 'forgot': 76,
 'stole': 77,
 'someone': 78,
 "account's": 79,
 'g': 80,
 'ive': 81,
 'own': 82,
 'havent': 83,
 "can't": 84,
 'f': 85,
 'ger': 86,
 'kl': 87,
 'd': 88,
 'j': 89,
 'h': 90,
 'creating': 91,
 'b': 92,
 'k': 93,
 'good': 94,
 'opening': 95,
 "i'd": 96,
 'update': 97,
 'n': 98,
 'has': 99,
 'm': 100,
 'edit': 101,
 'changes': 102,
 'meep': 103,
 'modify': 104,
 'cant': 105,
 'make': 106,
 'registering': 107,
 't': 108,
 'v': 109,
 'sfjksdhfkjshdf': 110,
 'sdfjkhsdfkj': 111,
 'skdjfshd': 112,
 'kfjshf': 113,
 'id': 114,
 'l': 115,
 'asdf': 116,
 'would': 117,
 'deleting': 118,
 'change': 119,
 "profile's": 120,
 'r': 121,
 'c': 122,
 'closing': 123,
 'removing': 124,
 'o': 125,
 'x': 126,
 'y': 127,
 'hf': 128,
 's': 129,
 'er': 130,
 "'": 131,
 'kjsdfhksdfjh': 132,
 'jhgjhghj': 133,
 'canceling': 134,
 'getting': 135,
 'resetting': 136,
 'recovering': 137,
 'gre': 138,
 'e': 139,
 'asd': 140,
 'fgj': 141,
 'not': 142,
 'df': 143,
 'iuy': 144,
 'asf': 145,
 'w': 146,
 'acount': 147,
 'fd': 148,
 'jhghjghj': 149,
 'lk': 150,
 'fg': 151,
 'ert': 152,
 'hj': 153,
 'sd': 154,
 'retrieving': 155,
 'erg': 156,
 'as': 157,
 'gfd': 158,
 'ksdfjh': 159,
 'kjsdfh': 160,
 'yu': 161,
 'sdg': 162,
 'htr': 163,
 'kfk': 164,
 'yg': 165,
 'ds': 166,
 'fgh': 167,
 'gg': 168,
 'kjhkjh': 169,
 'dfg': 170,
 'gh': 171,
 'dj': 172,
 'sdfsdf': 173,
 'dgh': 174,
 'cv': 175,
 'fh': 176,
 'hi': 177,
 'z': 178,
 'hb': 179,
 'jh': 180,
 'et': 181,
 'dfgh': 182,
 're': 183,
 'fo': 184,
 'jhgjhg': 185,
 'hfhf': 186,
 'gf': 187,
 'saf': 188,
 'kdkckdk': 189,
 'yes': 190,
 'xxx': 191,
 'pizza': 192,
 'qweqweqw': 193,
 'kokoko': 194,
 'dsf': 195,
 'cc': 196,
 'dg': 197,
 'wer': 198,
 'jjj': 199,
 'he': 200,
 'kjg': 201,
 'lh': 202,
 'jhg': 203,
 'sdf': 204,
 'hh': 205,
 'gdf': 206,
 'zxczx': 207,
 'fdg': 208,
 'rt': 209,
 'xx': 210,
 'jhgjghj': 211,
 'jf': 212,
 'fm': 213,
 'lorem': 214,
 'ipsum': 215,
 'dolor': 216,
 'sit': 217,
 'amet': 218,
 'consectetur': 219,
 'adipisicing': 220,
 'elit': 221,
 'sed': 222,
 'eiusmod': 223,
 'tempor': 224,
 'incididunt': 225,
 'ut': 226,
 'labore': 227,
 'dolore': 228,
 'magna': 229,
 'aliqua': 230,
 'vv': 231,
 'dfgdfg': 232,
 'fj': 233,
 'p': 234,
 'mn': 235,
 'fger': 236,
 'dfgdf': 237,
 'q': 238,
 'cvn': 239,
 'uy': 240,
 'uh': 241,
 'fe': 242,
 'reg': 243,
 'ehhhhhhhhhhh': 244,
 'is': 245,
 'fasdf': 246,
 'dasd': 247,
 'htrs': 248,
 'nm': 249,
 'gkjdfn': 250,
 'ggggg': 251,
 'nnnnnnnnnn': 252,
 'gfh': 253,
 'nnnnnnnnnnnnn': 254,
 'lkj': 255,
 'jjkl': 256,
 'kooko': 257,
 'jo': 258,
 'jhghj': 259,
 'jg': 260,
 'tr': 261,
 'rtyu': 262,
 'hjghjghj': 263,
 'hg': 264,
 'djdjdj': 265,
 'ug': 266,
 'guy': 267,
 'ff': 268,
 'jhgjhgh': 269,
 'ser': 270,
 'very': 271,
 '3r': 272,
 'jj': 273,
 'nnnnnnnn': 274,
 'sisis': 275,
 'lfks': 276,
 'ym': 277,
 'asdasdas': 278,
 'rev': 279,
 'jhghjg': 280,
 'nn': 281,
 'did': 282,
 'gfhg': 283,
 'iu': 284,
 'yuyu': 285,
 'doo': 286,
 'io': 287,
 'czx': 288,
 'were': 289,
 'watn': 290,
 'ot': 291,
 'pasword': 292,
 'ggg': 293,
 'awdadw': 294,
 'hvh': 295,
 'asdasd': 296,
 'retertert': 297,
 'jk': 298,
 'htrh': 299,
 'cffff': 300,
 'try': 301,
 'se': 302,
 'dfh': 303,
 'ncv': 304,
 'mxc': 305,
 'of': 306,
 'hhhh': 307,
 'gdfg': 308,
 'czxc': 309,
 'xxxxxxxxxxxxxx': 310,
 'fth': 311,
 'retretert': 312,
 'sdaf': 313,
 'okkoko': 314,
 'jhghghj': 315,
 'jhgjgh': 316,
 'jghjghj': 317,
 'erger': 318,
 'gert': 319,
 'fhg': 320,
 'ghfgh': 321,
 '4': 322,
 '5': 323,
 'jyt': 324,
 'bjjb': 325,
 'eg': 326,
 'mm': 327,
 'thanks': 328,
 'hgfhgf': 329,
 'kjh': 330,
 'ygu': 331,
 'hfghfg': 332,
 'djd': 333,
 'uu': 334,
 'lj': 335,
 'dsfg': 336,
 'gu': 337,
 'gv': 338,
 'thr': 339,
 '6u': 340,
 'ghf': 341,
 'fghfgh': 342,
 'ic': 343,
 'errwer': 344,
 'gdfgdfgdfg': 345,
 'ljk': 346,
 'adsf': 347,
 'sdfg': 348,
 'zx': 349,
 'your': 350,
 'asdasdasd': 351,
 'sa': 352,
 '2': 353,
 'wrtg': 354,
 'ggy': 355,
 'hgf': 356,
 'uuu': 357,
 'bbb': 358,
 'oi': 359,
 'we': 360,
 'zxv': 361,
 'wertyui': 362,
 'bv': 363,
 'fhr': 364,
 'hrt': 365,
 'ytyut': 366,
 'vre': 367,
 'use': 368,
 'tto': 369,
 'accountg': 370,
 'zccount': 371,
 'rceate': 372,
 'onlien': 373,
 'usre': 374,
 'craete': 375,
 'cann': 376,
 'wana': 377,
 'myprofile': 378,
 'making': 379,
 'dfgdfgd': 380,
 '6': 381,
 'ky': 382,
 'dwe': 383,
 'fer': 384,
 'cccccccccccccccc': 385,
 'asdas': 386,
 'jkl': 387,
 'klk': 388,
 'rr': 389,
 'gfdg': 390,
 'nnnnnnnnnnnnnnnnn': 391,
 'fsdf': 392,
 'xxxxx': 393,
 'ni': 394,
 'zsuwwhssh': 395,
 'sdfdsf': 396,
 'xix': 397,
 'gfhgfh': 398,
 'nnnnnnnnnnnn': 399,
 'zdfg': 400,
 'vhvh': 401,
 'in': 402,
 'ddthgg': 403,
 'kdhisejcsuvvsuvusgesu': 404,
 'bff': 405,
 'ft': 406,
 'dv': 407,
 'regerg': 408,
 "i'm": 409,
 'km': 410,
 'dfhd': 411,
 'yt': 412,
 'erth': 413,
 'mmmmmmmmmmmmmmmmmmm': 414,
 'ertertert': 415,
 'gsdf': 416,
 'gsg': 417,
 'st': 418,
 'gj': 419,
 'fklsdm': 420,
 'klfsdm': 421,
 'sdkjfn': 422,
 'sfg': 423,
 'hdgh': 424,
 'db': 425,
 '8': 426,
 'gdfjkn': 427,
 'gkdfjn': 428,
 'djkfn': 429,
 'gjkdfn': 430,
 'cjcuucj': 431,
 'fcghtd': 432,
 'gr': 433,
 'fsdfsdfsd': 434,
 'vfo': 435,
 'cov': 436,
 'vi': 437,
 'hgjhj': 438,
 'jkhkj': 439,
 'kjhkjhkj': 440,
 'kjhjkhj': 441,
 'jkhjkhkj': 442,
 'kjhjk': 443,
 'kj': 444,
 'fds': 445,
 'gfdgfdg': 446,
 'ry': 447,
 'slk': 448,
 'flsk': 449,
 'flskdj': 450,
 'jlkj': 451,
 'zxczxc': 452,
 'cjkl': 453,
 'je': 454,
 'klkl': 455,
 'retert': 456,
 'rtuwrtu': 457,
 'iuyjhghjgjhg': 458,
 'uhdjdj': 459,
 'djdisid': 460,
 'dnjd': 461,
 'gfhgfhgfh': 462,
 'vb': 463,
 'oo': 464,
 'fun': 465,
 'fjfbf': 466,
 'dmdnd': 467,
 'dm': 468,
 'kjn': 469,
 'kjhk': 470,
 'fgfgfg': 471,
 'sdfsdfsdfsdf': 472,
 'xbdbdbd': 473,
 'ci': 474,
 'setsetsets': 475,
 'fy': 476,
 'ghfh': 477,
 'tj': 478,
 'estestsset': 479,
 'cdjjcdh': 480,
 'ikl': 481,
 'rtrt': 482,
 'fge': 483,
 'hhhhhh': 484,
 'swtyestyd': 485,
 'okkokookko': 486,
 'be': 487,
 'asdasdasdasdasd': 488,
 'cvb': 489,
 'kljl': 490,
 'kfkcgk': 491,
 'ck': 492,
 'vvv': 493,
 'asb': 494,
 '3': 495,
 'gyu': 496,
 'iugh': 497,
 'mmmmmmmmmmmmm': 498,
 'sdfsdfsdfsd': 499,
 'dfgs': 500,
 'nnnnnnnnn': 501,
 'gkxfyiuofyifoudtidtuccgjxycyjxtkctjxukvhxvkgcxhkvxytc': 502,
 '9': 503,
 'w6u': 504,
 'jcjcj': 505,
 'tg': 506,
 'ji': 507,
 'hghg': 508,
 'jm': 509,
 'fasd': 510,
 'adwad': 511,
 'hk': 512,
 'chhh': 513,
 'sag': 514,
 'hssh': 515,
 'ob': 516,
 'nice': 517,
 'ohjllfmnnsm': 518,
 'asdfghj': 519,
 'jhghjgj': 520,
 'jhgjh': 521,
 'jhgjhgjh': 522,
 'jhgghj': 523,
 'hjgghj': 524,
 'bc': 525,
 'fc': 526,
 'fgsd': 527,
 'zzzzzzzzzzz': 528,
 'hhjj': 529,
 "l'": 530,
 'huh': 531,
 'dr': 532,
 'cvzxcv': 533,
 'aaaaaaaa': 534,
 'lquwwyyyssgs': 535,
 'hgkj': 536,
 'fk': 537,
 'fgfgfgf': 538,
 'bbbbbbbbbbbbb': 539,
 'hd': 540,
 'lkh': 541,
 'hdg': 542,
 'dgf': 543,
 'nd': 544,
 'fwr': 545,
 'gb': 546,
 'saytjvnnnnnk': 547,
 'fas': 548,
 'tcg': 549,
 'bb': 550,
 'uuobn': 551,
 'fsdfwefwer': 552,
 '23r': 553,
 'rw3r': 554,
 '3rr2rwe': 555,
 'rytdrfgdsf': 556,
 'sfsdfwe': 557,
 'fsdfwe': 558,
 'ggh': 559,
 'guil': 560,
 'gi': 561,
 'lkjlkj': 562,
 'djdj': 563,
 'aaaaaaaaaaa': 564,
 'gd': 565,
 'vyocitdiycudzyfyxgixyrcgjxugctuxvtuxrivyixtivyixiubhkxfibuixtbhkcut': 566,
 'hkxugbhixfu': 567,
 'jicugbivuf': 568,
 'ytr': 569,
 'guu': 570,
 'hgrt': 571,
 'ty': 572,
 'hfgh': 573,
 'cvg': 574,
 'sf': 575,
 'gffhgt': 576,
 'fa': 577,
 'zshwyyyyakzk': 578,
 'asdkryhstayayyy': 579,
 'sksks': 580,
 'setgsets': 581,
 'jljlkj': 582,
 'mmmmmmmmmmmm': 583,
 'lfkjs': 584,
 'flskd': 585,
 'dddddddddddas': 586,
 'jdhdhdhgjc': 587,
 'jhjk': 588,
 'uygb': 589,
 'nmhjb': 590,
 'uj': 591,
 'for': 592,
 'time': 593,
 'consideration': 594,
 'gjhg': 595,
 'es': 596,
 'kh': 597,
 'sldkj': 598,
 'jflskj': 599,
 'flskj': 600,
 'asssssssssss': 601,
 'ghjkldghjkl': 602,
 'weeeeeeeeeeeeeeeee': 603,
 'dfgd': 604,
 'vd': 605,
 'ertert': 606,
 'hgfdsdfgh': 607,
 'asdasda': 608,
 'xxxx': 609,
 'mmm': 610,
 'fjkp': 611,
 'fghfh': 612,
 'ehhhhhhhhhhhhh': 613,
 'ha': 614,
 'jd': 615,
 'hkl': 616,
 'vbn': 617,
 'kkkk': 618,
 'ytejtyjrtyjthyjey': 619,
 'sdfsf': 620,
 'sdjkfn': 621,
 'fkjsdn': 622,
 'jr': 623,
 'vn': 624,
 'gyg': 625,
 'chij': 626,
 'asda': 627,
 'fi': 628,
 'fdsfsdf': 629,
 'gjh': 630,
 'hfghgf': 631,
 'hfg': 632,
 'zzzz': 633,
 'hhhhhhh': 634,
 'huu': 635,
 'cxv': 636,
 'fwe': 637,
 'vc': 638,
 'ugi': 639,
 'asdasdasdasd': 640,
 'nzn': 641,
 'pp': 642,
 'ksusuysshzhzl': 643,
 'fhj': 644,
 'mmmmmmmmmmmmmmm': 645,
 'vgg': 646,
 'sda': 647,
 'go': 648,
 'dfcvfgvbgh': 649,
 'fdh': 650,
 'ge': 651,
 'vore': 652,
 'fre': 653,
 'avncituehl': 654,
 'dfgdfgdfgdfg': 655,
 'xxxxxxxxxxxxx': 656,
 'sadg': 657,
 'das': 658,
 'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm': 659,
 'shdhbdbbcbfbdbdbdbbdhbdhdhjdjdnndjjdjdjdnjdndnfnfjjfjjfjfjjddj': 660,
 'yh': 661,
 'uyg': 662,
 'vjxgcxutcyixucxtxdttiftjdtixvhkckycyj': 663,
 'hkcjyckyckyvykclucykv': 664,
 'hy': 665,
 'dfklgm': 666,
 'gkldfm': 667,
 'ke': 668,
 'ks': 669,
 'jew': 670,
 'cj': 671,
 'ggggggggg': 672,
 'kfkckf': 673,
 'fsdfsdf': 674,
 'fsdfsd': 675,
 'ii': 676,
 'fgsdg': 677,
 'sdfa': 678,
 'hjj': 679,
 'dfgdg': 680,
 'fdgdfgdfgdfg': 681,
 'af': 682,
 'ghg': 683,
 'ggu': 684,
 'by': 685,
 'dfdf': 686,
 'dth': 687,
 'ssh': 688,
 'jb': 689,
 'jhgjg': 690,
 'jfd': 691,
 'gfkhmyl': 692,
 'rtkh': 693,
 'ltrlh': 694,
 'lltrhm': 695,
 'sdfsfsf': 696,
 'dsv': 697,
 'gggg': 698,
 'zxc': 699,
 'gygy': 700,
 'ghju': 701,
 'fjre': 702,
 'tyv': 703,
 'vty': 704,
 'kv': 705,
 'hyl': 706,
 'hgj': 707,
 'dfgdfgdfg': 708,
 'ghj': 709,
 'vgb': 710,
 'asdasojdsakldlksadsadsada': 711,
 'vhjjj': 712,
 'hgg': 713,
 'rger': 714,
 'sdfsfsdf': 715,
 'iuhgjhgjhg': 716,
 'sdfghjkl': 717,
 'esrg': 718,
 'uiu': 719,
 'khz': 720,
 'vt': 721,
 'tu': 722,
 'kjgk': 723,
 'cry': 724,
 'iukj': 725,
 'hjkhkj': 726,
 'cx': 727,
 'sdfdsfdsf': 728,
 'jhgjhgjhg': 729,
 'vioer': 730,
 'rei': 731,
 'rejiv': 732,
 'eh': 733,
 'bhub': 734,
 'ioy': 735,
 'creae': 736,
 'nkow': 737,
 'cani': 738,
 'creaet': 739,
 'createone': 740,
 'suer': 741,
 'hjave': 742,
 'acocunt': 743,
 'accountand': 744,
 'eail': 745,
 'acconut': 746,
 'accoun': 747,
 'helpme': 748,
 'anaccount': 749,
 'reigster': 750,
 'fukcing': 751,
 'caqn': 752,
 'wher': 753,
 'hav': 754,
 'accvount': 755,
 'ican': 756,
 'asme': 757,
 'wat': 758,
 'onlineaccount': 759,
 'tyo': 760,
 'proflie': 761,
 'accout': 762,
 'accopunt': 763,
 'midn': 764,
 'cacount': 765,
 'profie': 766,
 'ned': 767,
 'ichanged': 768,
 'mny': 769,
 'editing': 770,
 'modifying': 771,
 'changing': 772,
 'updating': 773,
 'ben': 774,
 'apssword': 775,
 'pssword': 776,
 'passwlrd': 777,
 'hgghghghghghghhg': 778,
 'ufdhgjndfnvbhfdjvnjkmfgbdfg': 779,
 'dbdbdbd': 780,
 'gafsdhs': 781,
 'fsdhgdf': 782,
 'gfffcccd': 783,
 '2t': 784,
 'gtq64qyh5t2312': 785,
 'rty': 786,
 '4ht4gw': 787,
 'hjw4wtg': 788,
 'knlihbkuvjgch': 789,
 'ddddddddddddddddddddddd': 790,
 'hfy': 791,
 'sfgh': 792,
 'assa': 793,
 'asfg': 794,
 'ndjty': 795,
 'yuke6u7yk': 796,
 'rtrwtj': 797,
 'kmt': 798,
 'hjw': 799,
 'yjwetyjwety': 800,
 'fsdfsdfs': 801,
 'dfsdfsdfs': 802,
 'ghfghhhhhj': 803,
 'tdsdfghjoiuytrdfgh': 804,
 'gghjkkknnbvvcccv': 805,
 'tjdytdf': 806,
 'few': 807,
 'gddbfnlnhfwdjxsyljryhfrtihtethgd': 808,
 "fgfhjk'll": 809,
 'dfghjwerterthgjgghhgfdgh': 810,
 '5yyrfiijggb': 811,
 'nvcyhgtpjhv': 812,
 'hbn': 813,
 'non3': 814,
 'asadadas': 815,
 'zhzjiskwbxhdnfund': 816,
 'cisnbcc': 817,
 'hgjhghffhfgf': 818,
 'fghj': 819,
 'qwdqqdwwqwdqwdqwqdwqdwwqdwqd': 820,
 'sgddfgfdg': 821,
 'dfhghhj': 822,
 'nnnnnnnnnnnnnn': 823,
 'sdbfdgn': 824,
 'hytre': 825,
 'vggg': 826,
 'shsjdjsjdjdbd': 827,
 'kjgjgkj': 828,
 'refgregregr': 829,
 'vgyujhbn': 830,
 'ojbiuk': 831,
 'sdfsdfsdf': 832,
 'sfadsad': 833,
 'nsnshshss': 834,
 'vhjjnjgfcbj': 835,
 'qwewqeqw': 836,
 'asdassa': 837,
 'ewqeqw': 838,
 'bjvtyre': 839,
 'vdvcvxcx': 840,
 'dfgetertertre': 841,
 '147852': 842,
 'yessss': 843,
 'sgeyj': 844,
 'gcgchcv': 845,
 'klasndlkabsdlibalsda': 846,
 '46yu4u4wu45u656u': 847,
 'lklkl': 848,
 'hgdfghdfhj': 849,
 'eaeagegegeg': 850,
 'dfsdfdfsdf': 851,
 'jhfhgf': 852,
 'jsdgfuadsfkhfs': 853,
 'rfyguhjhyuj': 854,
 'gyfghb': 855,
 'gfhgfhgf': 856,
 'ererqewrrwe': 857,
 'kuyuyuky': 858,
 'vmjfduchb': 859,
 'fhhck': 860,
 'lifcbui': 861,
 'hgfhgfhgfhgfh': 862,
 'hfhfghfghfgh': 863,
 'gdfjfgfghg': 864,
 'nvcjgtflufdhtf': 865,
 '………': 866,
 '…': 867,
 'gfhvmfghmdhg': 868,
 'nlklh': 869,
 'vghjnrsh': 870,
 'mhgcdjhdf': 871,
 'rg': 872,
 'ywaaa': 873,
 'ckjyrdhg': 874,
 'bgj': 875,
 'ryjsrtj': 876,
 'trjtr': 877,
 'jitr': 878,
 'ijutr': 879,
 'jistyk': 880,
 'yktf': 881,
 'dfsdgf': 882,
 'ihkhk': 883,
 'yeryeyhfd': 884,
 'ddddddddddddddddddddd': 885,
 'gdfgfdgfdgfdgdgd': 886,
 'lkjlkjlkj': 887,
 'uuuuuuuuuuuuuuuuuuuuuuuuuu': 888,
 'uiyui': 889,
 'dd': 890,
 '34r5ty67u8i9o': 891,
 'dwadwadwafwwafadawdwa': 892,
 'kuykuyk': 893,
 'ftu67b8': 894,
 'ufiidykdykdydyudykydky': 895,
 'sksjsjsjsjsjsjsjajajwkwkwksksjs': 896,
 'eiryiuehf': 897,
 'dsiuhieuwrhf': 898,
 'kjhdkjfh': 899,
 'dsiufhewirouieowkfkjsdh': 900,
 'bvmxcn': 901,
 'vkhdsfkjds': 902,
 'fewhuhrewuk': 903,
 'bkjb': 904,
 'kjb': 905,
 'cghhgggg': 906,
 'jkhgkhkj': 907,
 'trdhujtd': 908,
 'hehhd': 909,
 'rtwr3wt': 910,
 'qtq3t3rwt': 911,
 'tw': 912,
 'tewtret': 913,
 'ertwesfgsgsdgsegdfgdfggsfgsdfg': 914,
 'sagsfd': 915,
 'lkhklhkl': 916,
 'fghjk': 917,
 'dfuhv': 918,
 'jsnd': 919,
 'djis': 920,
 'xjxjd': 921,
 'dnxid': 922,
 'ixjx': 923,
 'xnxiix': 924,
 'xnidbd': 925,
 'cn': 926,
 'bxfbvxc': 927,
 'ffg': 928,
 'uikiukukouik': 929,
 'uiokluiokloio': 930,
 'fgfhjj': 931,
 'rhdfjh': 932,
 'hdjdjdkdkkdkdjdj': 933,
 'cuz': 934,
 'fsdfsdfsdfsda': 935,
 '7ry': 936,
 'ewrwueoriuwe': 937,
 'kldjflkdsj': 938,
 'fsdoirueowiuroiew': 939,
 'sldjflksdjfds': 940,
 'loiruweoiruoe': 941,
 'fdlkdsjflkds': 942,
 'faoiueioqwulskjflska': 943,
 'doiquwewoiqulkdsjlksajd': 944,
 'asoieuqwoieasjdlkasjdlas': 945,
 'zdgzdf': 946,
 'sfjdajklsfdajklsfdjk': 947,
 'sdfasaffasdasdf': 948,
 'dhhebd': 949,
 'fbjdnd': 950,
 'didn’t': 951,
 'ejdjhe': 952,
 'diskette': 953,
 'ebsjhdjd': 954,
 'fgdfgdf': 955,
 'grds': 956,
 'ytghbjnm': 957,
 'tfghhghhhh': 958,
 'bgyyy': 959,
 'gdsjfdykigh': 960,
 'ncowefc': 961,
 'qeufbpef': 962,
 'efcubwef': 963,
 'ewufbwuep': 964,
 'there': 965,
 'gtydjuty': 966,
 'vgbhnj': 967,
 'cbdb': 968,
 'sstrstrstdygxhststjttystjtsst': 969,
 'rsehgrbs': 970,
 'sjsjj': 971,
 'teerg': 972,
 'sulfur': 973,
 'shy': 974,
 'hjghjhgj': 975,
 'dsfgdfg': 976,
 'hjmgkjgj': 977,
 'fdhjdh': 978,
 '34r3zwzwz': 979,
 'bxcbd': 980,
 'hjkj': 981,
 'hjhkj': 982,
 'jlhjk': 983,
 'kkjhjkhkh': 984,
 'ggdfgdfgdfg': 985,
 'shhdfjdbcbdbcbdkwpzbq': 986,
 'sjenxkabx': 987,
 'thyjkut': 988,
 'ujikuly': 989,
 'ujeiloritpi': 990,
 'uduguhd': 991,
 'dfjghdlkfg': 992,
 'jdfghd': 993,
 'fdflgjkdfij': 994,
 'djkfkdjfljd': 995,
 'fgjldlkfgdfgkjd': 996,
 'fgdflkg': 997,
 'dfjgdkjlfl': 998,
 'gdjkf': 999,
 'fcdcd': 1000,
 ...}

In [136]:
X = tokenizer.texts_to_sequences(df_main["Response"])
X

[[293],
 [778],
 [779],
 [780],
 [380],
 [781, 782],
 [783],
 [784, 785, 786, 381, 787, 788],
 [789],
 [790],
 [791, 382],
 [792],
 [793],
 [294],
 [242, 130, 86, 86, 138, 86, 86],
 [168],
 [794],
 [795, 796, 797, 798, 799, 800],
 [801, 802],
 [803],
 [804],
 [805],
 [108],
 [806],
 [383, 807, 384, 86, 86, 86, 86, 156],
 [808],
 [809, 93, 150],
 [810],
 [811, 812],
 [28, 813, 139, 814],
 [815],
 [816, 817],
 [818],
 [819],
 [820],
 [821],
 [822],
 [823],
 [824],
 [825],
 [826],
 [827],
 [828],
 [829, 121, 243],
 [830],
 [385],
 [831, 92, 125],
 [196, 122, 122, 196],
 [832],
 [833],
 [834],
 [835],
 [836, 837, 838, 386],
 [839],
 [840],
 [],
 [841],
 [842],
 [169],
 [843],
 [844],
 [845],
 [846],
 [],
 [847],
 [387, 87, 87, 87, 388, 848, 87],
 [121, 389, 121],
 [390, 849, 197],
 [850],
 [851],
 [852],
 [391],
 [853],
 [392],
 [854, 855],
 [856],
 [857],
 [858],
 [859],
 [860],
 [861],
 [862],
 [863],
 [864],
 [393],
 [394],
 [865, 89],
 [866, 867],
 [868],
 [869],
 [870],
 [871],
 [872],
 [873],
 [874, 175, 92],
 [875, 876, 877, 878, 879, 880, 881],
 [882, 883],
 [884],
 [885],
 [886],
 [887],
 [888],
 [889],
 [890],
 [891],
 [892],
 [893],
 [894],
 [895],
 [896],
 [897, 898, 899, 900, 901, 902, 903],
 [93, 904, 905],
 [395],
 [906],
 [907],
 [908],
 [244],
 [909],
 [910, 911, 198, 912, 913, 914],
 [915],
 [396],
 [916],
 [90],
 [199, 87, 87, 87, 87, 87, 87, 87],
 [917],
 [918, 90],
 [919, 920, 88, 921, 922, 923, 924, 88, 88, 397, 925, 85, 926],
 [88, 927],
 [928],
 [398, 176],
 [929, 930],
 [931],
 [168],
 [932],
 [389],
 [933],
 [934],
 [935],
 [399],
 [936],
 [937, 938, 939, 940, 941, 942, 943, 944, 945],
 [946, 400],
 [947],
 [948],
 [949, 950, 951, 952, 953, 954],
 [955],
 [956],
 [957],
 [958, 959],
 [960],
 [961, 962, 963, 964],
 [85, 401, 90, 90, 295, 177, 1, 965, 245, 28, 7, 402, 4],
 [966],
 [967, 100],
 [403],
 [404],
 [405, 968],
 [969],
 [970],
 [971],
 [972, 88, 973, 974, 406],
 [975],
 [976],
 [122],
 [977],
 [978],
 [979],
 [980],
 [981, 982, 983, 984],
 [985],
 [986, 987],
 [988, 989, 990],
 [991, 151, 992, 993, 994, 995, 996, 997, 998, 999, 80],
 [1000],
 [1001],
 [1002, 1003, 1004, 1005, 1006],
 [1007],
 [1008],
 [1009, 1010, 1011, 1012],
 [296],
 [200, 88, 1013, 407],
 [408],
 [1014],
 [88, 140, 246, 140, 157],
 [1015],
 [1016],
 [1017],
 [1018],
 [1019, 1020],
 [1021],
 [85],
 [1022],
 [1023, 1024],
 [1025],
 [1026],
 [1027, 1028, 1029],
 [126],
 [1030],
 [247, 140, 140, 1031, 157],
 [1032],
 [1033],
 [1034],
 [1035, 1036, 1037, 1038, 1039],
 [297],
 [1040],
 [1041],
 [1042, 298, 1043, 28, 409, 402, 410],
 [1044],
 [1045, 1046, 1047, 1048, 1049, 1050, 1051],
 [1052, 411],
 [201, 1053],
 [1054],
 [412, 1055],
 [1056],
 [1057, 1058, 148, 1059, 1060, 1061, 115, 1062],
 [127],
 [1063],
 [1064],
 [1065, 1066, 1067],
 [1068],
 [1069],
 [1070, 1071],
 [248, 299, 413],
 [1072],
 [1073],
 [414],
 [1074, 126],
 [1075],
 [202, 1076],
 [415],
 [1077, 407, 200],
 [1078],
 [1079],
 [1080, 92, 1081],
 [178],
 [1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089],
 [1090],
 [1091, 1092],
 [300],
 [1093, 179, 180],
 [116,
  12,
  1094,
  1095,
  416,
  1096,
  417,
  418,
  127,
  301,
  301,
  181,
  1097,
  1098,
  1099,
  1100],
 [1101, 203, 419, 1102],
 [1103],
 [1104],
 [1105],
 [1106],
 [1107, 131, 131],
 [1108, 1109, 1110, 1111],
 [1112],
 [1113],
 [1114,
  1115,
  420,
  420,
  421,
  421,
  1116,
  1117,
  1118,
  1119,
  1120,
  1121,
  1122,
  1123,
  204,
  1124,
  1125,
  1126,
  1127,
  422,
  1128,
  1129,
  1130],
 [1131, 1132],
 [1133],
 [1134],
 [1135, 1136, 93],
 [1137],
 [1138],
 [1139, 85, 1140, 1141, 302, 1142],
 [1143],
 [249, 1144, 1145, 1146, 108, 85, 1147],
 [1148],
 [1149],
 [1150],
 [1151, 1152],
 [423,
  1153,
  1154,
  1155,
  1156,
  182,
  85,
  1157,
  424,
  182,
  303,
  303,
  197,
  304,
  1158,
  170,
  1159,
  171,
  425,
  1160],
 [198],
 [1161],
 [92, 1162, 1163, 80, 1, 90, 1164, 1165],
 [1166, 1167, 426],
 [1168,
  1169,
  1170,
  1171,
  427,
  428,
  428,
  427,
  250,
  250,
  1172,
  1173,
  429,
  250,
  250,
  430,
  1174,
  430,
  1175,
  1176,
  1177,
  1178,
  183],
 [1179],
 [1180],
 [1181],
 [246],
 [1182, 1183, 1184],
 [1185],
 [305, 1186],
 [158],
 [431],
 [1187, 1188],
 [1189],
 [1190],
 [432],
 [1191],
 [1192],
 [1193],
 [1194, 1195, 1196, 1197, 433],
 [1198],
 [1199],
 [1200, 1201, 1202],
 [1203],
 [1204],
 [434],
 [1205],
 [1206],
 [1207],
 [1208],
 [88],
 [1209],
 [1210],
 [1211],
 [1212,
  1213,
  184,
  306,
  435,
  1214,
  184,
  184,
  1215,
  1216,
  184,
  1217,
  1218,
  1219,
  1220,
  1221,
  436,
  1222,
  1223,
  1224,
  437,
  1225,
  1226,
  436,
  1227,
  1228],
 [85],
 [251, 307, 205],
 [1229],
 [1230],
 [1231],
 [1232, 1233],
 [1234],
 [1235, 1236],
 [1237],
 [438,
  1238,
  1239,
  439,
  440,
  1240,
  441,
  1241,
  442,
  1242,
  1243,
  442,
  1244,
  1245,
  443,
  443,
  444],
 [1246],
 [1247, 1248],
 [1249],
 [1250],
 [1251],
 [12],
 [1252, 1253, 1254, 1255],
 [1256],
 [1257, 1258, 1259, 1260],
 [1261, 1262],
 [1263],
 [1264],
 [1265],
 [252],
 [1266, 1267, 1268, 1269],
 [1270, 1271],
 [],
 [1272],
 [1273],
 [1274],
 [1275],
 [1276],
 [1277],
 [1278],
 [1279],
 [1280],
 [1281, 85, 1282, 143],
 [1283],
 [1284, 253, 1285, 1286],
 [1287, 1288, 1289, 1290],
 [254],
 [1291],
 [1292],
 [1293],
 [1294],
 [1295],
 [1296],
 [1297, 445, 1298, 308, 148, 206, 446, 1299, 206, 206, 1300],
 [1],
 [1301],
 [1302, 1303, 1304, 1305, 1306, 109],
 [1307],
 [1308],
 [1309, 1310, 1311],
 [1312],
 [1313, 1314],
 [1315, 447],
 [1316, 1317, 1318, 1319],
 [1320],
 [159, 110, 111, 112, 113, 160],
 [1321, 1322],
 [1323, 448, 449, 450, 1324, 451, 85],
 [452, 207, 207, 309],
 [208],
 [1325],
 [310],
 [1326],
 [126, 1327],
 [1328],
 [1329],
 [1330],
 [1331, 144, 1332, 1333],
 [1334],
 [1335, 1336, 311, 311],
 [92],
 [1337],
 [255],
 [453],
 [312],
 [454, 1338, 1339],
 [1340],
 [1341],
 [256, 87, 455, 87, 87, 455, 87],
 [1342],
 [109],
 [127, 1343, 1344, 1345],
 [1346, 1347, 1348, 1349, 1350, 1351, 1352],
 [1353],
 [1354, 209, 1355, 121, 1356],
 [1357],
 [456, 1358, 1359, 1360],
 [1361],
 [244],
 [1362],
 [1363],
 [1364, 1365],
 [1366],
 [1367, 1368, 1369, 1370, 457, 1371, 1372, 1373, 457, 1374, 1375, 1376, 1377],
 [1378],
 [1379],
 [1380],
 [1381],
 [1382],
 [1383],
 [185, 1384, 1385, 458, 1386],
 [1387],
 [1388, 1389, 1390, 1391],
 [1392, 1393, 1394, 1395],
 [1396],
 [459, 460, 85, 461],
 [245, 1397],
 [1398, 1399, 161],
 [116, 313, 116, 140],
 [1400],
 [1401],
 [1402],
 [1403],
 [1404],
 [159, 110, 111, 112, 113, 132, 110, 111, 112, 113, 160],
 [1405],
 [1406],
 [1407, 1408],
 [1409],
 [1410, 1411],
 [1412],
 [257, 314],
 [1413],
 [151],
 [462],
 [92, 1414, 1415, 1416, 1417, 1418, 1419],
 [258, 1420, 1421, 1422],
 [1423],
 [1424, 12, 1425],
 [1426, 1427, 1428, 1429],
 [1430],
 [1431],
 [1432],
 [1433],
 [141, 141, 141],
 [210],
 [1434],
 [1435],
 [1436],
 [1437, 463],
 [1438],
 [1439, 1440, 1441],
 [1442],
 [1443],
 [1444],
 [1445],
 [1446,
  211,
  1447,
  149,
  133,
  1448,
  315,
  316,
  1449,
  169,
  317,
  149,
  1450,
  1451,
  211,
  185,
  259,
  180],
 [1452, 1453, 1454],
 [1455],
 [100],
 [464],
 [1456],
 [1457, 1458],
 [1459,
  1460,
  12,
  1461,
  1462,
  186,
  1463,
  1464,
  1465,
  260,
  465,
  85,
  466,
  212,
  80,
  1466,
  467,
  468,
  1467,
  1468,
  213,
  1469,
  212,
  1470],
 [1471, 1472, 89, 1473, 1474],
 [1475],
 [1476],
 [1477, 1478, 1479, 1480, 1481, 1482],
 [1483, 1484],
 [1485,
  214,
  215,
  216,
  217,
  218,
  219,
  220,
  221,
  222,
  6,
  223,
  224,
  225,
  226,
  227,
  181,
  228,
  229,
  230],
 [1486, 1487, 1488, 1489, 1490],
 [1491],
 [162, 1492, 1493, 1494],
 [139],
 [1495],
 [1496],
 [1497],
 [1498],
 [1499],
 [1500],
 [1501, 131],
 [1502],
 [1503],
 [1504],
 [1505],
 [465, 1506, 1507, 98, 98, 1508],
 [115, 469],
 [1509],
 [1510],
 [1511, 1512, 1513],
 [1514],
 [1515],
 [242, 187, 318, 86, 138, 86, 319],
 [1516],
 [1517, 470, 1518, 1519, 1520, 1521, 1522, 1523, 1524],
 [1525],
 [1526, 1527, 1528],
 [231, 1529],
 [1530],
 [1531, 1532, 1533, 1534],
 [261],
 [471],
 [1535],
 [310],
 [1536],
 [1537],
 [1538],
 [1539, 109],
 [1540],
 [1541,
  1542,
  1543,
  1544,
  1545,
  1546,
  1547,
  1548,
  1549,
  1550,
  1551,
  1552,
  1553,
  1554],
 [1555],
 [294],
 [125, 1556],
 [1557, 143],
 [1558],
 [1559],
 [85],
 [1560],
 [472],
 [1561],
 [473, 1562, 1563, 85, 1564, 1565],
 [1566],
 [474, 1567, 1568],
 [1569],
 [1570],
 [1571],
 [475],
 [1572],
 [178, 88, 196],
 [94, 80],
 [1573],
 [1574],
 [1575],
 [1576, 1577, 152],
 [1578, 1579, 1580, 1581, 122, 1582, 1583, 122],
 [476, 1584, 1585, 1586],
 [477],
 [1587],
 [1588],
 [1589],
 [1590],
 [1591],
 [1592],
 [1593],
 [1594, 320, 320],
 [1595],
 [1596],
 [478, 1597, 1598, 1599, 1600],
 [479],
 [1601],
 [14, 480],
 [1602],
 [1603, 262, 262, 1604],
 [1605],
 [1606],
 [1607],
 [1608],
 [1609],
 [1610],
 [1611],
 [1612, 1613],
 [263, 1614, 169, 1615, 149, 439, 1616, 1617, 1618, 1619, 1620],
 [1621],
 [1622, 1623, 1624, 1625],
 [26,
  186,
  12,
  19,
  1626,
  1627,
  88,
  186,
  1628,
  128,
  85,
  128,
  466,
  186,
  90,
  128,
  85,
  212,
  1629,
  1630,
  1631,
  1632,
  186],
 [1633, 1634],
 [1635],
 [1636],
 [246],
 [1637, 1638, 1639],
 [1640],
 [1641],
 [1642],
 [80],
 [1643, 258, 481, 1644, 1645, 1646, 1647, 1648, 1649],
 [1650],
 [1651],
 [1652],
 [1653, 482, 209, 209],
 [1654],
 [1655],
 [483, 1656, 86, 152, 1657, 90, 1658],
 [1659],
 [1660],
 [1661],
 [1662],
 [1663, 85, 1664, 1665],
 [1666, 484, 1667, 1668, 1669, 1670],
 [1671],
 [264, 1672, 1673],
 [1674],
 [1675],
 [1676, 1677, 1678],
 [321],
 [1679],
 [1680, 1681, 1682, 1683, 156, 1684],
 [322, 323, 381],
 [1685],
 [1686],
 [1687, 1688, 1689, 93],
 [1690],
 [1691],
 [1692, 1693, 1694],
 [1695],
 [1696],
 [1697],
 [1698],
 [1699],
 [1700],
 [1701],
 [1702],
 [1703],
 [1704],
 [1705, 127, 1706],
 [1707],
 [485],
 [1708, 1709, 1710],
 [178],
 [1711],
 [1712],
 [71, 5, 1713],
 [1714],
 [1715, 188, 1716, 145, 1717],
 [1718],
 [257, 486],
 [1719],
 [1720, 121, 1721],
 [1722, 1723, 80],
 [12],
 [1724, 1725, 1726, 90, 1727, 295],
 [1728],
 [1729],
 [163, 1730, 324],
 [108, 1731],
 [1732, 1733, 1734],
 [1735],
 [1736],
 [1737, 1738],
 [1739, 325, 199, 487, 1740],
 [1741, 1742, 1743],
 [488],
 [1744],
 [1745, 1746, 1747, 1748],
 [100, 100, 100],
 [1749],
 [1750],
 [1751, 1752, 1753, 1754, 1755, 1756],
 [1757, 1758, 1759, 1760, 1761, 1762],
 [1763, 1764],
 [89],
 [489],
 [1765],
 [265],
 [1766],
 [1767],
 [1768],
 [490],
 [1769],
 [50],
 [326],
 [1770],
 [1771],
 [1772, 1773],
 [126, 98],
 [266, 1774, 1775, 1776],
 [1777],
 [491,
  164,
  189,
  85,
  492,
  89,
  491,
  164,
  93,
  1778,
  1779,
  1780,
  164,
  1,
  1781,
  1782,
  1783,
  189,
  189,
  164,
  164,
  1784,
  1785,
  1786,
  1787],
 [1788],
 [1789],
 [1790],
 [493],
 [1791],
 [1792],
 [484],
 [116],
 [1793],
 [1794, 1795],
 [1796],
 [1797, 1798],
 [1799],
 [109, 1800],
 [1801],
 [1802],
 [1803],
 [1804, 1805, 1806],
 [1807],
 [327],
 [94, 1808],
 [328],
 [1809],
 [140, 1810, 494, 88, 99, 1811, 109],
 [1812],
 [153, 1813],
 [1814],
 [126],
 [1815],
 [232],
 [158, 1816, 1817, 1818, 1819],
 [1820],
 [1821, 1822, 1823, 1824],
 [1825, 1826],
 [1827],
 [1828],
 [185],
 [495],
 [1829, 1830],
 [1831, 115],
 [1832],
 [1833, 1834, 1835],
 [1836],
 [1837],
 [1838],
 [496, 1839, 1840, 1841, 267, 1842],
 [1843, 1844],
 [1845],
 [1846],
 [115, 1847],
 [1848],
 [1849],
 [329],
 [1850],
 [1851, 1852, 1853, 1854, 1855],
 [1856, 1857],
 [1858],
 [1859],
 [1860, 497, 1861, 1862, 1863],
 [1, 71, 1864, 1865],
 [1866],
 [1867, 1868],
 [1869],
 [1870],
 [1871],
 [1872],
 [1873, 1874],
 [1875],
 [1876],
 [1877],
 [1878],
 [1879],
 [1880, 108, 88, 122, 1881, 1882],
 [1883],
 [1884],
 [1885],
 [1886, 1887, 1888],
 [1889],
 [330],
 [1890],
 [1891],
 [98],
 [1892, 1893, 1894, 1895, 1896, 1897, 1898],
 [190],
 [1899, 331, 1900, 80, 1901],
 [1902],
 [1903,
  1904,
  1905,
  1906,
  1907,
  1908,
  1909,
  1910,
  1911,
  1912,
  1913,
  1914,
  1915,
  1916,
  1917,
  1918,
  1919,
  1920],
 [1921],
 [1922, 1923, 80, 1924, 1925],
 [1926],
 [1927, 1928, 1929, 1930],
 [248, 163],
 [1931, 1932],
 [1933],
 [1934],
 [498],
 [196],
 [1935],
 [1936,
  1937,
  1938,
  12,
  1939,
  1940,
  1941,
  92,
  1942,
  1943,
  1944,
  1945,
  100,
  1946,
  213,
  1947,
  85],
 [1948],
 [1949],
 [1950],
 [1951],
 [1952],
 [1953],
 [1954],
 [1955],
 [1956],
 [1957],
 [1958],
 [1959],
 [1960],
 [1961],
 [187, 332, 1962],
 [499],
 [1963],
 [1964],
 [1965, 1966],
 [1967],
 [1968],
 [93],
 [1969],
 [98, 1970, 1971],
 [1972],
 [1973],
 [1974],
 [1975],
 [1976],
 [1977, 1978, 1979, 1980, 1981, 1982, 1983],
 [1984],
 [1985],
 [1986],
 [500, 1987],
 [1988],
 [129],
 [1989],
 [1990],
 [501],
 [1991, 1992],
 [502],
 [],
 [1993],
 [1994],
 [1995, 1996],
 [1997, 92],
 [1998],
 [1999],
 [2000],
 [2001],
 [248, 163, 163],
 [2002],
 [109],
 [2003, 2004, 2005, 165, 202, 80],
 [2006],
 [2007, 2008],
 [2009, 2010, 90, 122],
 [2011, 2012, 2013, 2014],
 [2015, 2016, 2017, 333, 2018, 2019, 2020, 126, 2021, 126, 2022, 126],
 [2023, 2024, 334, 2025],
 [2026],
 [168],
 [2027],
 [2028],
 [2029],
 [393],
 [2030],
 [2031, 2032, 2033, 2034, 2035],
 [2036],
 [90],
 [2037, 100, 2038, 2039, 2040, 322, 503, 2041, 2042, 504, 2043, 2044],
 [2045],
 [2046],
 [505],
 [2047, 2048, 1, 6],
 [2049],
 [2050, 506],
 [2051],
 [108],
 [90],
 [109],
 [2052],
 [89, 507, 394],
 [2053],
 [2054, 166, 204, 2055],
 [2056],
 [2057, 2058, 2059, 2060, 2061, 153],
 [2062, 89, 327, 100],
 [2063],
 [2064],
 [2065, 2066, 2067, 1, 2068, 2069, 2070, 2071, 2072, 2073, 90],
 [2074, 89],
 [508],
 [2075],
 [205],
 [2076],
 [92],
 [2077, 2078],
 [2079],
 [2080, 2081, 2082],
 [80, 2083, 98, 268, 2084],
 [2085],
 [509, 2086],
 [2087],
 [2088],
 [2089],
 [2090, 92],
 [2091, 16, 2092],
 [190, 2093],
 [2094],
 [2095],
 [510],
 [2096],
 [511],
 [2097],
 [512, 2098, 2099, 335],
 [2100],
 [2101],
 [100],
 [2102, 14],
 [2103],
 [2104, 2105, 2106, 2107, 2108, 2109, 178, 2110, 2111],
 [2112],
 [2113],
 [2114],
 [513],
 [2115],
 [2116],
 [2117, 2118, 26, 2119, 2120],
 [188, 145, 188, 2121, 514, 162, 129, 197],
 [2122],
 [2123],
 [2124, 2125, 2126, 2127],
 [2128,
  2129,
  167,
  2130,
  2131,
  2132,
  2133,
  2134,
  2135,
  336,
  2136,
  2137,
  2138,
  167],
 [],
 [2139],
 [323, 2140, 2141],
 [515],
 [2142],
 [410, 100, 100],
 [2143],
 [2144, 516],
 [2145],
 [2146],
 [2147],
 [2148],
 [2149],
 [517, 518],
 [2150, 2151, 2152],
 [2153],
 [2154, 337, 2155],
 [2156, 2157, 2158],
 [2159],
 [2160],
 [2161],
 [2162],
 [2163],
 [519],
 [2164],
 [2165],
 [2166],
 [133,
  269,
  2167,
  315,
  315,
  2168,
  520,
  133,
  521,
  2169,
  522,
  211,
  523,
  524,
  2170,
  133,
  185,
  211,
  524],
 [2171, 2172],
 [2173],
 [2174],
 [128, 161, 2175, 2176, 2177, 267],
 [2178],
 [2179],
 [2180, 2181],
 [175, 525],
 [2182, 338],
 [2183],
 [2184, 2185],
 [2186, 2187, 2188, 2189, 2190],
 [2191, 2192],
 [139, 2193, 526, 2194, 2195, 92, 338, 2196, 2197, 338, 2198, 2199],
 [2200],
 [2201, 2202, 527, 2203, 2204],
 [2205, 2206],
 [2207, 2208],
 [432],
 [2209],
 [2210],
 [2211],
 [2212],
 [528],
 [2213],
 [2214],
 [2215, 487, 92, 92, 92, 2216],
 [2217],
 [2218, 2219, 2220, 298, 2221],
 [2222],
 [2223],
 [2224],
 [2225],
 [2226],
 [2227, 2228],
 [2229],
 [2230],
 [529],
 [162],
 [2231],
 [2232],
 [2233, 530, 2234, 100],
 [2235],
 [2236],
 [2237],
 [2238],
 [2239, 2240],
 [2241, 2242],
 [2243, 2244, 2245, 2246, 2247],
 [2248],
 [2249, 531, 531, 28],
 [2250, 532, 209, 2251],
 [2252],
 [93],
 [2253],
 [2254],
 [327],
 [2255],
 [2256],
 [2257],
 [2258],
 [2259],
 [2260, 2261],
 [2262],
 [2263],
 [533, 2264, 2265],
 [2266],
 [108],
 [534],
 [2267, 2268, 2269, 2270],
 [2271],
 [2272],
 [],
 [2273],
 [2274],
 [2275, 2276, 2277, 2278, 2279],
 ...]

In [137]:
dummy=0
for i in X:
    if len(i)>dummy:
        dummy=len(i)
max_len=dummy
max_len

39

In [138]:
X = pad_sequences(X, maxlen=max_len, padding="pre")
X

array([[  0,   0,   0, ...,   0,   0, 293],
       [  0,   0,   0, ...,   0,   0, 778],
       [  0,   0,   0, ...,   0,   0, 779],
       ...,
       [  0,   0,   0, ...,   4,  30,  38],
       [  0,   0,   0, ...,   4,   2,  30],
       [  0,   0,   0, ...,   3,   1,   6]])

In [139]:
from sklearn.model_selection import train_test_split

In [140]:
X_train, X_test, y_train, y_test = train_test_split(X, df_main["Label"], test_size=25,random_state=0)

In [142]:
import keras

In [146]:
model = keras.models.Sequential([
    keras.layers.Embedding(vocab, 64),
    keras.layers.GlobalAveragePooling1D(),
    keras.layers.Dense(64, activation="relu"),
    keras.layers.Dropout(rate=0.25),
    keras.layers.Dense(32, activation="relu"),
    keras.layers.Dropout(rate=0.25),
    keras.layers.Dense(1, activation="sigmoid")
])

In [147]:
model.compile(optimizer="adam",loss='binary_crossentropy',metrics=["acc"])

In [148]:
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test),  verbose=1)

Epoch 1/10
235/235 [==============================] - 10s 36ms/step - loss: 0.2606 - acc: 0.8935 - val_loss: 0.0047 - val_acc: 1.0000
Epoch 2/10
235/235 [==============================] - 8s 34ms/step - loss: 0.0079 - acc: 0.9985 - val_loss: 3.3908e-04 - val_acc: 1.0000
Epoch 3/10
235/235 [==============================] - 8s 35ms/step - loss: 0.0044 - acc: 0.9988 - val_loss: 1.9431e-04 - val_acc: 1.0000
Epoch 4/10
235/235 [==============================] - 8s 34ms/step - loss: 0.0018 - acc: 0.9995 - val_loss: 9.8302e-05 - val_acc: 1.0000
Epoch 5/10
235/235 [==============================] - 9s 39ms/step - loss: 0.0014 - acc: 0.9997 - val_loss: 6.4884e-05 - val_acc: 1.0000
Epoch 6/10
235/235 [==============================] - 8s 35ms/step - loss: 6.5971e-04 - acc: 0.9997 - val_loss: 1.0315e-05 - val_acc: 1.0000
Epoch 7/10
235/235 [==============================] - 8s 35ms/step - loss: 7.6854e-04 - acc: 0.9999 - val_loss: 1.1971e-05 - val_acc: 1.0000
Epoch 8/10
235/235 [==============================] - 8s 34ms/step - loss: 9.0730e-04 - acc: 0.9996 - val_loss: 1.2530e-05 - val_acc: 1.0000
Epoch 9/10
235/235 [==============================] - 8s 35ms/step - loss: 3.0260e-04 - acc: 1.0000 - val_loss: 7.5328e-06 - val_acc: 1.0000
Epoch 10/10
235/235 [==============================] - 8s 34ms/step - loss: 4.6635e-04 - acc: 0.9997 - val_loss: 1.0197e-05 - val_acc: 1.0000

In [149]:
y_predict=model.predict(X_test)

1/1 [==============================] - 0s 269ms/step

In [151]:
y_predict=y_predict>0.5

In [155]:
from sklearn.metrics import accuracy_score,classification_report

In [154]:
accuracy_score(y_predict,y_test)

1.0

In [156]:
print(classification_report(y_predict,y_test))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00        13
        True       1.00      1.00      1.00        12

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25